name: rapidd_technologies_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  firebase_ui_firestore: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  google_sign_in: 6.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
